name: EDFlib

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

env:
  EDFLIB_VERSION: 1.23
  COMMIT_SHA1: 4a80d07427acb64d2c3a07d8ce704b11b6832a0f
  BUILD_TYPE: Release
  INSTALL_PREFIX: install

jobs:
  build-msvc:
    if: >-
      github.event.pull_request.draft == false

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [ Win32, x64 ]
        linkage: [ dynamic, static ]
        include:
          - generator: Visual Studio 17 2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clone EDFlib
      run: |
        git clone https://gitlab.com/Teuniz/EDFlib.git
        pushd EDFlib
        git reset --hard ${{ env.COMMIT_SHA1 }}
        popd

    - name: Copy CMakeLists.txt
      run: |
        Copy-Item CMakeLists.txt -Destination .\EDFlib

    - name: Configure
      run: >
        cmake
        -G "${{ matrix.generator }}"
        -A ${{ matrix.arch }}
        -S EDFlib
        -B build
        ${{ matrix.linkage == 'dynamic' && '-DBUILD_SHARED_LIBS=ON' || '-DBUILD_SHARED_LIBS=OFF' }}
        -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }}

    - name: Build & Install
      run: |
        cmake --build build --config ${{ env.BUILD_TYPE }} --target install

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EDFlib-v${{ env.EDFLIB_VERSION }}-${{ matrix.arch }}-${{ matrix.linkage }}
        path: ${{ env.INSTALL_PREFIX }}

  release:
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: windows-latest

    needs: [ build-msvc ]

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: List downloaded files
      run: ls -R

    - name: Create archives
      run: |
        7z a EDFlib-v${{ github.ref_name }}-Win32-dynamic.zip .\EDFlib-v${{ env.EDFLIB_VERSION }}-Win32-dynamic\*
        7z a EDFlib-v${{ github.ref_name }}-Win32-static.zip .\EDFlib-v${{ env.EDFLIB_VERSION }}-Win32-static\*
        7z a EDFlib-v${{ github.ref_name }}-x64-dynamic.zip .\EDFlib-v${{ env.EDFLIB_VERSION }}-x64-dynamic\*
        7z a EDFlib-v${{ github.ref_name }}-x64-static.zip .\EDFlib-v${{ env.EDFLIB_VERSION }}-x64-static\*

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        generate_release_notes: true
        files: |
          EDFlib*.zip
